# sensores iott
ni=6
# base de eventos por sensor (sensor i genera base * i eventos)
base_eventos=10
# clasificadores
nc=1
# ervidores de consolidación y despliegue
ns=3
# caocity buzón para clasificación
tam1=5
# capcityde cada buzón de consolidación
tam2=5
